### ISSUE TITLE
Separate Zephyr and Zephyr SDK from this repo

### ISSUE THREAD

**Issue by poussa** [01org/CODK-M#37]
Would it be possible to use existing trees and directories for Zephyr and Zephyr SDK and just rely on them via Zephyr environment variables:

ZEPHYR_SDK_INSTALL_DIR
ZEPHYR_BASE
ZEPHYR_GCC_VARIANT

Now the Makefile is downloading separate copies of those tools. You can reuse the existing Zephr and Zephyr SDK, or ask users to install them separately including the correct version numbers.

**Comment by bigdinotech** [comment]
We actually have a few changes on top of Vanilla Zephyr which is why we need our own copy of the Zephyr.
